use strum::EnumIter;

use crate::utils::actions::KeyAction;

#[derive(EnumIter, Debug, Clone, Copy, PartialEq)]
pub enum ComplexAction {
    // Part 1: Mouse & Movement
    MouseLeft,
    MouseRight,
    MouseMiddle,
    Forward,
    Back,
    Dpi,
    WheelForward,
    WheelBack,
    WheelLeft,
    WheelRight,
    ScrollUp,
    ScrollDown,
    XUp,
    XDown,
    YUp,
    YDown,
    // Part 2: Media & System
    PreviousTrack,
    NextTrack,
    Stop,
    PlayPause,
    Player,
    Firepower,
    Mute,
    VolumeDown,
    VolumeUp,
    Calculator,
    FnSmall,
    Mail,
    MyComputer,
    Search,
    Home,
    BrightnessDecrease,
    BrightnessIncrease,
    SiriActivation,
    RecoilControl,
    RecoilControlContinuous,
    RecoilControlToggle,
    WeaponSwitchIncrease,
    WeaponSwitchDecrease,
    WeaponSwitchLoop,
    SystemPower,
    SystemSleep,
    WakeUp,
    // Part 3: Symbols & Shortcuts
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    SwitchInputMethod,
    ZoomOut,
    ZoomIn,
    AiFunction,
    MicrophoneSwitch,
    BackAlternative,
    FnLockScreen,
    LockScreen,
    RightFn,
    Fn,
    VolKbBrightness,
    VolKbBrightness2,
    VolKbBrightness3,
    Refresh,
    ProgramOpen1,
    ProgramOpen2,
    ProgramOpen3,
    DpiLoop,
    DpiPlus,
    DpiMinus,
    DpiShift,
    ProfileValue,
    ProfilePlus,
    ProfileMinus,
    ProfileLoop,
    ProfileExchange,
    ProfileExchange2,
    ProfileExchange3,
    ProfileExchange4,
    ProfileExchange5,
    OpenWebsite,
    WinE,
    WinTab,
    WinD,
}

impl ComplexAction {
    pub fn values(&self) -> [u8; 4] {
        match self {
            Self::MouseLeft => [1, 0, 240, 0],
            Self::MouseRight => [1, 0, 241, 0],
            Self::MouseMiddle => [1, 0, 242, 0],
            Self::Forward => [1, 0, 244, 0],
            Self::Back => [1, 0, 243, 0],
            Self::Dpi => [20, 0, 0, 0],
            Self::WheelForward => [1, 0, 247, 0],
            Self::WheelBack => [1, 0, 248, 0],
            Self::WheelLeft => [1, 0, 245, 0],
            Self::WheelRight => [1, 0, 246, 0],
            Self::ScrollUp => [1, 0, 245, 1],
            Self::ScrollDown => [1, 0, 245, 255],
            Self::XUp => [1, 0, 246, 251],
            Self::XDown => [1, 0, 246, 5],
            Self::YUp => [1, 0, 247, 251],
            Self::YDown => [1, 0, 247, 5],
            Self::PreviousTrack => [3, 0, 182, 0],
            Self::NextTrack => [3, 0, 181, 0],
            Self::Stop => [3, 0, 183, 0],
            Self::PlayPause => [3, 0, 205, 0],
            Self::Player => [3, 0, 131, 1],
            Self::Firepower => [11, 0, 0, 0],
            Self::Mute => [3, 0, 226, 0],
            Self::VolumeDown => [3, 0, 234, 0],
            Self::VolumeUp => [3, 0, 233, 0],
            Self::Calculator => [3, 0, 146, 1],
            Self::FnSmall => [10, 1, 0, 0],
            Self::Mail => [3, 0, 138, 1],
            Self::MyComputer => [3, 0, 148, 1],
            Self::Search => [3, 0, 33, 2],
            Self::Home => [3, 0, 35, 2],
            Self::BrightnessDecrease => [3, 0, 112, 0],
            Self::BrightnessIncrease => [3, 0, 111, 0],
            Self::SiriActivation => [18, 0, 227, 44],
            Self::RecoilControl => [22, 4, 0, 0],
            Self::RecoilControlContinuous => [22, 6, 0, 0],
            Self::RecoilControlToggle => [22, 7, 0, 0],
            Self::WeaponSwitchIncrease => [22, 1, 0, 0],
            Self::WeaponSwitchDecrease => [22, 2, 0, 0],
            Self::WeaponSwitchLoop => [22, 3, 0, 0],
            Self::SystemPower => [2, 129, 0, 0],
            Self::SystemSleep => [2, 130, 0, 0],
            Self::WakeUp => [2, 131, 0, 0],
            Self::LeftParen => [0, 0, 229, 38],
            Self::RightParen => [0, 0, 229, 39],
            Self::LeftBrace => [0, 225, 47, 0],
            Self::RightBrace => [0, 225, 48, 0],
            Self::SwitchInputMethod => [0, 224, 44, 0],
            Self::ZoomOut => [0, 0, 227, 45],
            Self::ZoomIn => [0, 0, 227, 46],
            Self::AiFunction => [0, 227, 225, 114],
            Self::MicrophoneSwitch => [6, 128, 0, 0],
            Self::BackAlternative => [3, 0, 36, 2],
            Self::FnLockScreen => [10, 13, 0, 0],
            Self::LockScreen => [0, 0, 227, 15],
            Self::RightFn => [10, 1, 1, 0],
            Self::Fn => [10, 1, 0, 0],
            Self::VolKbBrightness => [10, 15, 0, 0],
            Self::VolKbBrightness2 => [10, 13, 0, 0],
            Self::VolKbBrightness3 => [10, 14, 0, 0],
            Self::Refresh => [3, 0, 39, 2],
            Self::ProgramOpen1 => [6, 128, 0, 1],
            Self::ProgramOpen2 => [6, 128, 0, 2],
            Self::ProgramOpen3 => [6, 128, 0, 3],
            Self::DpiLoop => [20, 0, 0, 0],
            Self::DpiPlus => [20, 0, 1, 0],
            Self::DpiMinus => [20, 0, 2, 0],
            Self::DpiShift => [20, 0, 4, 0],
            Self::ProfileValue => [8, 0, 0, 0],
            Self::ProfilePlus => [8, 0, 1, 0],
            Self::ProfileMinus => [8, 0, 2, 0],
            Self::ProfileLoop => [8, 0, 3, 0],
            Self::ProfileExchange => [8, 0, 4, 0],
            Self::ProfileExchange2 => [8, 0, 4, 1],
            Self::ProfileExchange3 => [8, 0, 4, 2],
            Self::ProfileExchange4 => [8, 0, 4, 3],
            Self::ProfileExchange5 => [8, 0, 4, 4],
            Self::OpenWebsite => [18, 0, 0, 0],
            Self::WinE => [0, 0, 227, 8],
            Self::WinTab => [0, 0, 227, 43],
            Self::WinD => [0, 0, 227, 7],
        }
    }
}

impl KeyAction for ComplexAction {
    fn to_bytes(&self) -> [u8; 4] {
        self.values()
    }

    fn legend(&self) -> String {
        format!("{:?}", self)
    }
}
