use strum::EnumIter;

use crate::utils::actions::KeyAction;

#[derive(EnumIter, Debug, Clone, Copy, PartialEq)]
#[repr(u8)]
pub enum KeyCode {
    None = 0,
    Mouse = 1, // When using parameters, can have mouse effects
    A = 4,
    B = 5,
    C = 6,
    D = 7,
    E = 8,
    F = 9,
    G = 10, // Or Fn when used with parameter 1
    H = 11,
    I = 12,
    J = 13,
    K = 14,
    L = 15,
    M = 16,
    N = 17,
    O = 18,
    P = 19,
    Q = 20,
    R = 21,
    S = 22,
    T = 23,
    U = 24,
    V = 25,
    W = 26,
    X = 27,
    Y = 28,
    Z = 29,
    Key1 = 30,
    Key2 = 31,
    Key3 = 32,
    Key4 = 33,
    Key5 = 34,
    Key6 = 35,
    Key7 = 36,
    Key8 = 37,
    Key9 = 38,
    Key0 = 39,
    Enter = 40,
    Esc = 41,
    BackSpace = 42,
    Tab = 43,
    Space = 44,
    Minus = 45,
    Equal = 46,
    LeftBracket = 47,
    RightBracket = 48,
    Backslash = 49,
    Semicolon = 51,
    Quote = 52,
    Backtick = 53,
    Comma = 54,
    Period = 55,
    Slash = 56,
    CapsLock = 57,
    F1 = 58,
    F2 = 59,
    F3 = 60,
    F4 = 61,
    F5 = 62,
    F6 = 63,
    F7 = 64,
    F8 = 65,
    F9 = 66,
    F10 = 67,
    F11 = 68,
    F12 = 69,
    Print = 70,
    ScrLk = 71,
    Pause = 72,
    Home = 74,
    PgUp = 75,
    Del = 76,
    End = 77,
    PgDown = 78,
    Right = 79,
    Left = 80,
    Down = 81,
    Up = 82,
    NumLk = 83,
    NumDiv = 84,
    NumMul = 85,
    NumMin = 86,
    NumAdd = 87,
    NumEnter = 88,
    Num1 = 89,
    Num2 = 90,
    Num3 = 91,
    Num4 = 92,
    Num5 = 93,
    Num6 = 94,
    Num7 = 95,
    Num8 = 96,
    Num9 = 97,
    Num0 = 98,
    NumPeriod = 99,
    Ctrl = 224,
    Shift = 225,
    Alt = 226,
    Win = 227,
    RightCtrl = 228,
    RightShift = 229,
    // Fn = 167837696, (0x0A010000)
}

impl KeyAction for KeyCode {
    fn to_bytes(&self) -> [u8; 4] {
        [0, 0, 0, *self as u8]
    }

    fn legend(&self) -> String {
        match self {
            KeyCode::Backtick => "`".to_string(),
            KeyCode::Minus => "-".to_string(),
            KeyCode::Equal => "=".to_string(),
            KeyCode::LeftBracket => "[".to_string(),
            KeyCode::RightBracket => "]".to_string(),
            KeyCode::Backslash => "\\".to_string(),
            KeyCode::Semicolon => ";".to_string(),
            KeyCode::Quote => "'".to_string(),
            KeyCode::Comma => ",".to_string(),
            KeyCode::Period => ".".to_string(),
            KeyCode::Slash => "/".to_string(),
            KeyCode::Key0 | KeyCode::Num0 => "0".to_string(),
            KeyCode::Key1 | KeyCode::Num1 => "1".to_string(),
            KeyCode::Key2 | KeyCode::Num2 => "2".to_string(),
            KeyCode::Key3 | KeyCode::Num3 => "3".to_string(),
            KeyCode::Key4 | KeyCode::Num4 => "4".to_string(),
            KeyCode::Key5 | KeyCode::Num5 => "5".to_string(),
            KeyCode::Key6 | KeyCode::Num6 => "6".to_string(),
            KeyCode::Key7 | KeyCode::Num7 => "7".to_string(),
            KeyCode::Key8 | KeyCode::Num8 => "8".to_string(),
            KeyCode::Key9 | KeyCode::Num9 => "9".to_string(),
            KeyCode::NumEnter => "↵".to_string(),
            KeyCode::NumAdd => "+".to_string(),
            KeyCode::NumMin => "-".to_string(),
            KeyCode::NumDiv => "÷".to_string(),
            KeyCode::NumMul => "×".to_string(),
            KeyCode::NumPeriod => ".".to_string(),
            KeyCode::RightCtrl => "Ctrl".to_string(),
            KeyCode::RightShift => "Shift".to_string(),
            KeyCode::Left => "←".to_string(),
            KeyCode::Right => "→".to_string(),
            KeyCode::Up => "↑".to_string(),
            KeyCode::Down => "↓".to_string(),
            _ => format!("{:?}", self),
        }
    }
}
