use super::actions::KeyCode;

#[derive(Debug, Clone, Copy)]
pub struct PositionedKey {
    pub key: KeyCode,
    pub matrix_index: u8,
    pub x: i32,
    pub y: i32,
    pub w: u32,
    pub h: u32,
}

pub trait KeyboardLayoutExt {
    /// Find key by KeyCode
    fn find_by_key(&self, key: KeyCode) -> Option<&PositionedKey>;

    /// Find key by matrix position
    fn find_by_matrix(&self, index: u8) -> Option<&PositionedKey>;
}

impl KeyboardLayoutExt for KeyboardLayout {
    fn find_by_key(&self, key: KeyCode) -> Option<&PositionedKey> {
        self.iter().find(|pk| pk.key == key)
    }

    fn find_by_matrix(&self, index: u8) -> Option<&PositionedKey> {
        self.iter().find(|pk| pk.matrix_index == index)
    }
}

pub type KeyboardLayout = [PositionedKey];

pub const KEYBOARD_LAYOUT: &KeyboardLayout = &[
    // Column 0
    PositionedKey {
        key: KeyCode::Esc,
        matrix_index: 0,
        x: 20,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Backtick,
        matrix_index: 1,
        x: 20,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Tab,
        matrix_index: 2,
        x: 20,
        y: -109,
        w: 57,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::CapsLock,
        matrix_index: 3,
        x: 20,
        y: -149,
        w: 67,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Shift,
        matrix_index: 4,
        x: 20,
        y: -189,
        w: 88,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Ctrl,
        matrix_index: 5,
        x: 20,
        y: -229,
        w: 51,
        h: 38,
    },
    // Column 1
    PositionedKey {
        key: KeyCode::Key1,
        matrix_index: 7,
        x: 61,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Q,
        matrix_index: 8,
        x: 80,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::A,
        matrix_index: 9,
        x: 90,
        y: -149,
        w: 38,
        h: 38,
    },
    // Column 2
    PositionedKey {
        key: KeyCode::F1,
        matrix_index: 12,
        x: 102,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Key2,
        matrix_index: 13,
        x: 102,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::W,
        matrix_index: 14,
        x: 121,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::S,
        matrix_index: 15,
        x: 131,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Z,
        matrix_index: 16,
        x: 111,
        y: -189,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Win,
        matrix_index: 17,
        x: 73,
        y: -229,
        w: 51,
        h: 38,
    },
    // Column 3
    PositionedKey {
        key: KeyCode::F2,
        matrix_index: 18,
        x: 143,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Key3,
        matrix_index: 19,
        x: 142,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::E,
        matrix_index: 20,
        x: 162,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::D,
        matrix_index: 21,
        x: 171,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::X,
        matrix_index: 22,
        x: 152,
        y: -189,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Alt,
        matrix_index: 23,
        x: 126,
        y: -229,
        w: 51,
        h: 38,
    },
    // Column 4
    PositionedKey {
        key: KeyCode::F3,
        matrix_index: 24,
        x: 183,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Key4,
        matrix_index: 25,
        x: 183,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::R,
        matrix_index: 26,
        x: 202,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::F,
        matrix_index: 27,
        x: 212,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::C,
        matrix_index: 28,
        x: 193,
        y: -189,
        w: 38,
        h: 38,
    },
    // Column 5
    PositionedKey {
        key: KeyCode::F4,
        matrix_index: 30,
        x: 224,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Key5,
        matrix_index: 31,
        x: 224,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::T,
        matrix_index: 32,
        x: 243,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::G,
        matrix_index: 33,
        x: 253,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::V,
        matrix_index: 34,
        x: 234,
        y: -189,
        w: 38,
        h: 38,
    },
    // Column 6
    PositionedKey {
        key: KeyCode::F5,
        matrix_index: 36,
        x: 284,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Key6,
        matrix_index: 37,
        x: 265,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Y,
        matrix_index: 38,
        x: 284,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::H,
        matrix_index: 39,
        x: 294,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::B,
        matrix_index: 40,
        x: 275,
        y: -189,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Space,
        matrix_index: 41,
        x: 179,
        y: -229,
        w: 243,
        h: 38,
    },
    // Column 7
    PositionedKey {
        key: KeyCode::F6,
        matrix_index: 42,
        x: 325,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Key7,
        matrix_index: 43,
        x: 305,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::U,
        matrix_index: 44,
        x: 325,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::J,
        matrix_index: 45,
        x: 335,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::N,
        matrix_index: 46,
        x: 315,
        y: -189,
        w: 38,
        h: 38,
    },
    // Column 8
    PositionedKey {
        key: KeyCode::F7,
        matrix_index: 48,
        x: 366,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Key8,
        matrix_index: 49,
        x: 346,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::I,
        matrix_index: 50,
        x: 366,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::K,
        matrix_index: 51,
        x: 375,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::M,
        matrix_index: 52,
        x: 356,
        y: -189,
        w: 38,
        h: 38,
    },
    // Column 9
    PositionedKey {
        key: KeyCode::F8,
        matrix_index: 54,
        x: 407,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Key9,
        matrix_index: 55,
        x: 387,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::O,
        matrix_index: 56,
        x: 407,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::L,
        matrix_index: 57,
        x: 416,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Comma,
        matrix_index: 58,
        x: 397,
        y: -189,
        w: 38,
        h: 38,
    },
    // Column 10
    PositionedKey {
        key: KeyCode::F9,
        matrix_index: 60,
        x: 467,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Key0,
        matrix_index: 61,
        x: 428,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::P,
        matrix_index: 62,
        x: 447,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Semicolon,
        matrix_index: 63,
        x: 457,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Period,
        matrix_index: 64,
        x: 438,
        y: -189,
        w: 38,
        h: 38,
    },
    PositionedKey {
        // TODO: find a way to use the ComplexAction Fn (or another way)
        key: KeyCode::None,
        matrix_index: 65,
        x: 424,
        y: -229,
        w: 51,
        h: 38,
    },
    // Column 11
    PositionedKey {
        key: KeyCode::F10,
        matrix_index: 66,
        x: 508,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Minus,
        matrix_index: 67,
        x: 468,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::LeftBracket,
        matrix_index: 68,
        x: 488,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Quote,
        matrix_index: 69,
        x: 498,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Slash,
        matrix_index: 70,
        x: 479,
        y: -189,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::RightCtrl,
        matrix_index: 71,
        x: 477,
        y: -229,
        w: 51,
        h: 38,
    },
    // Column 12
    PositionedKey {
        key: KeyCode::F11,
        matrix_index: 72,
        x: 548,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Equal,
        matrix_index: 73,
        x: 509,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::RightBracket,
        matrix_index: 74,
        x: 529,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::RightShift,
        matrix_index: 76,
        x: 519,
        y: -189,
        w: 67,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Left,
        matrix_index: 77,
        x: 548,
        y: -229,
        w: 38,
        h: 38,
    },
    // Column 13
    PositionedKey {
        key: KeyCode::F12,
        matrix_index: 78,
        x: 589,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::BackSpace,
        matrix_index: 79,
        x: 550,
        y: -69,
        w: 77,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Backslash,
        matrix_index: 80,
        x: 570,
        y: -109,
        w: 57,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Enter,
        matrix_index: 81,
        x: 539,
        y: -149,
        w: 88,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Up,
        matrix_index: 82,
        x: 589,
        y: -189,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Down,
        matrix_index: 83,
        x: 589,
        y: -229,
        w: 38,
        h: 38,
    },
    // Column 14 (Navigation)
    PositionedKey {
        key: KeyCode::Home,
        matrix_index: 84,
        x: 641,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::PgUp,
        matrix_index: 85,
        x: 641,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::PgDown,
        matrix_index: 86,
        x: 641,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::End,
        matrix_index: 87,
        x: 641,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Right,
        matrix_index: 89,
        x: 630,
        y: -229,
        w: 38,
        h: 38,
    },
    // Column 15 (Numpad Links)
    PositionedKey {
        key: KeyCode::Pause,
        matrix_index: 90,
        x: 691,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::NumLk,
        matrix_index: 91,
        x: 691,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Num7,
        matrix_index: 92,
        x: 691,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Num4,
        matrix_index: 93,
        x: 691,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Num1,
        matrix_index: 94,
        x: 691,
        y: -189,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Num0,
        matrix_index: 95,
        x: 691,
        y: -229,
        w: 77,
        h: 38,
    },
    // Column 16 (Numpad Midden)
    PositionedKey {
        key: KeyCode::ScrLk,
        matrix_index: 96,
        x: 732,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::NumDiv,
        matrix_index: 97,
        x: 732,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Num8,
        matrix_index: 98,
        x: 732,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Num5,
        matrix_index: 99,
        x: 732,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Num2,
        matrix_index: 100,
        x: 732,
        y: -189,
        w: 38,
        h: 38,
    },
    // Column 17 (Numpad Rechts)
    PositionedKey {
        key: KeyCode::Print,
        matrix_index: 102,
        x: 773,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::NumMul,
        matrix_index: 103,
        x: 773,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Num9,
        matrix_index: 104,
        x: 773,
        y: -109,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Num6,
        matrix_index: 105,
        x: 773,
        y: -149,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::Num3,
        matrix_index: 106,
        x: 773,
        y: -189,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::NumPeriod,
        matrix_index: 107,
        x: 773,
        y: -229,
        w: 38,
        h: 38,
    },
    // Column 18 (Numpad Rand)
    PositionedKey {
        key: KeyCode::Del,
        matrix_index: 108,
        x: 814,
        y: -20,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::NumMin,
        matrix_index: 109,
        x: 814,
        y: -69,
        w: 38,
        h: 38,
    },
    PositionedKey {
        key: KeyCode::NumAdd,
        matrix_index: 110,
        x: 814,
        y: -109,
        w: 38,
        h: 78,
    },
    PositionedKey {
        key: KeyCode::NumEnter,
        matrix_index: 112,
        x: 814,
        y: -189,
        w: 38,
        h: 77,
    },
];
